// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramBot.DataBase;

#nullable disable

namespace TelegramBot.Migrations
{
    [DbContext(typeof(TelegramBotContext))]
    [Migration("20220525134818_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramBot.DataBase.Models.Bot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Название бота");

                    b.Property<long>("TelegramBotId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_bot_id")
                        .HasComment("id телеграм бота");

                    b.HasKey("Id");

                    b.ToTable("bot");

                    b.HasComment("Телеграм боты");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BotId")
                        .HasColumnType("integer")
                        .HasColumnName("bot_id")
                        .HasComment("id бота");

                    b.Property<int>("TypeMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("type_menu_id")
                        .HasComment("id типа меню");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value")
                        .HasComment("Значение кнопки меню");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("TypeMenuId");

                    b.ToTable("menu");

                    b.HasComment("Меню(кнопки выбора) бота");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.TypeMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Тип меню");

                    b.HasKey("Id");

                    b.ToTable("type_menu", (string)null);

                    b.HasComment("Типы меню");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email")
                        .HasComment("Почта пользователя");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname")
                        .HasComment("Ник пользователя");

                    b.Property<int>("UserBotId")
                        .HasColumnType("integer")
                        .HasColumnName("user_bot_id")
                        .HasComment("Пользователи телеграм");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasComment("Пользователи");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.UserSettings", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("Дата создания");

                    b.HasKey("MenuId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("user_settings");

                    b.HasComment("Настройки пользователей");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.Menu", b =>
                {
                    b.HasOne("TelegramBot.DataBase.Models.Bot", "Bot")
                        .WithMany("Menus")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBot.DataBase.Models.TypeMenu", "TypeMenu")
                        .WithMany("Menus")
                        .HasForeignKey("TypeMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("TypeMenu");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.UserSettings", b =>
                {
                    b.HasOne("TelegramBot.DataBase.Models.Menu", "Menu")
                        .WithMany("UserSettingsList")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBot.DataBase.Models.User", "User")
                        .WithMany("UserSettingsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.Bot", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.Menu", b =>
                {
                    b.Navigation("UserSettingsList");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.TypeMenu", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("TelegramBot.DataBase.Models.User", b =>
                {
                    b.Navigation("UserSettingsList");
                });
#pragma warning restore 612, 618
        }
    }
}
